### PR TITLE
Feature/scrum 3592

### PR DESCRIPTION
**Pull request by tlm**

### CODE REVIEW

**Review by GKTheOne — COMMENTED** [review]
I'm not sure you really need to bake a docker image with the test data as the test data seems really small/quick to load. Setting up the ripe-test-db in compose you could just mount the config/init into a mysql image, save having to build an extra image/etc.

If you're worried about data persistence, that's what volumes are for. :)

Speaking of which, might be good to add named volumes to the compose file for all the 'anonymous' volumes, eg, volume from the mysql base image. I hate having to cleanup volumes when they are all 2987349623874562398y6arkgfhghgd... etc.

**Comment by tlm** [comment]
You are correct. It was originally much more complicated hence the docker image. All though leaving it as a Dockerfile at the moment makes it much easier to work with from Maven and saves doubling up config.

I would be inclined to leave it for the sheer fact of Maven. Thoughts @GKTheOne ?

**Comment by GKTheOne** [comment]
Does the test-data image get/will be used as a sidecar container for the unit/integration tests then?
 Cause that makes more sense then. (I'm not worried either way on this issue, but the less people have to do manually the better)

My main concern however is the volumes created. Unnamed volumes are messy, not only in listing but also prevents you from cleaning waste data but keeping the good data. eg, the whois compose stuff will name it's volumes (db + maven repo) so you can trash the db but keep the maven repo or vice versa as needed. And because they are named I can separate them from volumes from other projects/etc.

**Comment by codebje** [comment]
Vault is included here because the internal CI builder project cannot trivially add it - if you remove it, you'll need to solve that problem there.  I'd suggest solving that problem _before_ removing it here :-)

**Comment by tlm** [comment]
@GKTheOne is that ok for the named volumes?

**Comment by tomhrr** [comment]
Closed, covered by https://github.com/APNIC-net/whowas-service/pull/14.

**Pull request closed without merging**
